#!/bin/bash

CLONE_DIR="$HOME/dotfiles"
BACKUP_DIR="$HOME/dotfiles_backup"
REPO_URL="git@github.com:rob-judith/dotfiles.git"


git clone "$REPO_URL" "$CLONE_DIR"
mkdir "$BACKUP_DIR"

# Detect the operating system and ensure tools are installed
if [[ "$OSTYPE" == "linux-gnu"* ]]; then
    # Assuming Ubuntu or a Debian-based distro
    echo "Detected Linux. Installing tools using apt..."

    sudo apt update
    sudo apt install -y fish fzf ripgrep tmux fd-find
    sh -c "$(curl -fsSL https://starship.rs/install.sh)"
    # Fix fdfind name
    fish -c "alias fd='fdfind'; funcsave fd"

elif [[ "$OSTYPE" == "darwin"* ]]; then
    # macOS
    echo "Detected macOS. Installing tools using Homebrew..."

    # Check if Homebrew is installed, install if we don't have it
    if test ! $(which brew); then
        echo "Homebrew not found. Installing..."
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    fi

    # Update Homebrew recipes
    brew update

    # Install the tools
    brew install fish fzf ripgrep tmux starship fd
else
    echo "Unsupported operating system."
    exit 1
fi

echo "Installation of tools complete!"
echo "Configuring dotfiles"

# Initialize and update submodules (for Tmux plugins or other submodule-managed configurations)
cd "$CLONE_DIR"
git submodule update --init --recursive
cd "$HOME"

# Create symlinks for dotfiles
DOTFILES=("vimrc" "tmux.conf" "gitconfig" "bashrc" "gitignore" "bash_profile")
for file in "${DOTFILES[@]}"; do
    mv "$HOME/.$file" "$BACKUP_DIR/$file"
    ln -s "$CLONE_DIR/$file" "$HOME/.$file"
done

# Symlink fish config (assuming your config is in a directory named ".config/fish")
if [ ! -d "$HOME/.config" ]; then
    mkdir "$HOME/.config"
fi
if [ ! -d "$HOME/.config/fish" ]; then
    mkdir "$HOME/.config/fish"
fi
mv "$HOME/.config/fish/config.fish" "$BACKUP_DIR/config.fish"
ln -s "$CLONE_DIR/fish/config.fish" "$HOME/.config/fish/config.fish"

# Symlink starship toml
ln -s "$CLONE_DIR/starship.toml" "$HOME/.config/starship.toml"

# Create symlinks for dot folders
for folder in "tmux" "vim"; do
    # Remove simlink if it exists
    if [ -L "$HOME/.$folder" ]; then
        rm "$HOME/.$folder"
    fi
    if [-d "$HOME/.$FOLDER" ]; then
        mv "$HOME/.$folder" "$BACKUP_DIR/$folder"
    fi
    ln -s "$CLONE_DIR/$folder/" "$HOME/.$folder"
done

# Install Vim plugins
vim +PlugInstall +qall
echo "Dotfiles and plugins installed"
